/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.itemis;

import java.io.PrintStream;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        UserInputReader input = new UserInputReader(new Scanner(System.in), new UserInputHandler(), new ResultDisplayer(), new PrintStream(System.out));
        input.readUserInput();
    }
}
