/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.itemis;

import java.io.PrintStream;
import java.util.HashMap;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {


        MetalCreditsRepository metalCreditsRepository = new MetalCreditsRepository(
                new RomanToCreditsCalculator(),
                new RomanExpressionBuilder(new GalacticRomanRepository())
                );
        UserInputHandler userInputHandler = new UserInputHandler(
                new GalacticRomanRepository(),
                metalCreditsRepository,
                new RomanToCreditsCalculator(), new MetalToCreditsCalculator(), new GalacticToCreditsCalculator( new RomanExpressionBuilder( new GalacticRomanRepository()), new RomanToCreditsCalculator()));
        UserInputReader input = new UserInputReader(
                new Scanner(System.in),
                userInputHandler,
                new ResultDisplayer(),
                new PrintStream(System.out));
        input.readUserInput();
    }
}
